## script for calculating the averaged drift rate per bout, keeping the dive id for checking the bottom time of the rest


##' .. content for \description{} (no empty lines) ..
##'
##' .. content for \details{} ..
##' @title 
##' @param DF el jodido datafram,e
##' @param zetas zeta value form the kalman filter to accept o reject a dive
##' @param bout.crit max difference between two dives to be on the same bout
##' @param prev.crit number of dives to check for bottom time before the bout
##' @param Data a data.frame generated by a postkalman call 
##' @return 
##' @author fer
driftBout <- function(PK, zetas = .98, bout.crit=10, prev.crit = 10){
    data <- PK[PK$zetas >= zetas, ]
    data$bout <- rep(1,nrow(data))
    for (i in 2:nrow(data)){
        if (data[i,c('dive')] < (data[(i-1),c('dive')] + bout.crit)) {
            data$bout[i] = data$bout[i-1]
        } else {
            data$bout[i] = data$bout[i-1] + 1
        }
    }
    
    bout <- NULL
    mini <- NULL
    maxi <- NULL
    tot <- NULL
    mdrift <- NULL                      #median drift rate
    mbot <- NULL                        #median bototm time previous
    mbot2 <- NULL
    timi <- NULL
    for (i in data$bout){
        sub <- data[data$bout==i, ]
        bout[i] <- i
        mini[i] <- min(sub$dive)
        maxi[i] <- max(sub$dive)
        tot[i] <- nrow(sub)
        mdrift[i] <- median(sub$NDE)
        endi <- min(sub$dive) - 1
        boti <- Data[Data$dive > (endi-20), ]
        boti <- boti[boti$dive <= endi, ]
        mbot[i] <- median(boti$prop.bottom)
        mbot2[i] <- median(boti$max.bottom)
        timi[i] <- median(boti$Date)
        }

    out <- data.frame(bout=bout,min=mini,max=maxi,tot=tot,mdrift=mdrift,
                      mbot = mbot,mbot2=mbot2, time=timi)


    out$delta <- 0
    for (i in 2:nrow(out)){
        out$delta[i] <- (out$mdrift[i] - out$mdrift[i-1]) / (out$time[i] - out$time[i-1])
        }
                      
    return(out)
}



out

plot(out$delta,out$mbot)
abline(lm(out$mbot~out$delta))
summary(lm(out$mbot~out$delta))


## voy a filtrar un delta,el peor]

out <- out[-which(out)]

which(out$delta == min(out$delta))

out <- out[-which(out$delta == min(out$delta)),]

## voy a jugar con el .95 que me da mas gracias, de momento
nrow(PK[PK$zetas > .95, ])
