##' Function for generating some dive metrics from High resolution time-depth profiles
##'
##' Different dive metrics are extracted from Hig resolution time depth profiles.
##' @title HR dive metric generation
##' @param Data a Dataset, ideally generated by hrsum
##' @param bc threshold for defining the bottom time of the dive
##' @return a data frame with some dive metrics
##' @author Fer Arce
hrmetrics <- function(Data, bc=.8){
    mat <- matrix(NA,ncol=12,nrow=max(Data$dive))
    sampling <- as.numeric(difftime(Data$Date[2],Data$Date[1],units='secs'))
    for (i in 1:max(Data$dive)){
        tmp.dive <- Data[Data$dive==i,] # This dive is selected
        mat[i,1] <- i
        mat[i,2] <- min(tmp.dive$Date)  #estos dos podrian ir de la mano juntos utilizando algo asi coo mat[i,c(2,3)] <-quantile(tmp.dive,c(0,1))
        mat[i,3] <- max(tmp.dive$Date)
        mat[i,4] <- max(tmp.dive$Depth)
        tmp.dive1 <- tmp.dive[tmp.dive$Depth>10,] # that's the real diving part
        mat[i,5]=as.numeric(difftime(max(tmp.dive1$Date),min(tmp.dive1$Date), units='secs')) + sampling
        b.c <- bc*max(tmp.dive1$Depth)
        mat[i,6] <- mean(tmp.dive1$Depth > b.c)
        tmp.dive2 <- tmp.dive[tmp.dive$Depth<10,]
        ##start <- min(tmp.dive1$Date[tmp.dive1$Depth > b.c])
        ##end <- max(tmp.dive1$Date[tmp.dive1$Depth > b.c])
        mat[i,7] <- as.numeric(difftime(max(tmp.dive1$Date[tmp.dive1$Depth > b.c]),min(tmp.dive1$Date[tmp.dive1$Depth > b.c]), units = 'secs')) + sampling
        ##drifting[i] <- mean(abs(tmp.dive$Speed) < .2) # only if speed is present
        mat[i,8]=real.dive1=as.numeric(difftime(max(tmp.dive2$Date),min(tmp.dive2$Date), units='secs'))+ sampling ## total duration, in seconds, excluding the survace interval after the dive
        mat[i,9] <- sd(tmp.dive1$Depth[tmp.dive1$Depth>b.c]) / mean(tmp.dive1$Depth[tmp.dive1$Depth>b.c])
        tmp.dive3 <- tmp.dive[tmp.dive$Depth >= b.c,  ]
        v1 <- diff(tmp.dive3$Depth)
        v2 <- abs(diff(diff(tmp.dive3$Depth)))
        mat[i,10] <- var(abs(v1), na.rm=TRUE) / mean(v1, na.rm=TRUE)
        mat[i,11] <- var(v2, na.rm=TRUE) / mean(v2, na.rm=TRUE)
        mat[i,12] <- mean(v1 > 0, na.rm=TRUE) # change on trajectory
    }
    mat <- as.data.frame(mat)
    names(mat) <- c('dive','start.time','end.time','max.depth','DIVE_DUR','bt','bt2','SUR_DUR','cvbot','cvdiff1','cvdiff2','sc')
    mat$start.time <- as.POSIXct(mat$start.time,tz='GMT',origin = "1970-01-01")
    mat$end.time <- as.POSIXct(mat$end.time,tz='GMT',origin = "1970-01-01")
    mat$bt2 <- mat$bt2/mat$DIVE_DUR
    mat$fday <- as.numeric(difftime(mat$start.time,  min(Data$Date), units='secs'))/86400
    mat$nday <- floor(mat$fday)
    return(mat)
}
